[package]
name = "stats"
version = "0.6.0"
authors = ["Vincent Foley <vfoley@gmail.com>"]
edition = "2018"
license = "mit"
homepage = "https://github.com/gnuvince/stats"
repository = "https://github.com/gnuvince/stats"

[dependencies]
getopts = "0.2"
separator = "0.4"
fast-float = "0.2"
